# -*- coding: utf-8 -*-
"""MD5_Hashing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fFc1NjpizPNJWB-S8IgNj7jt6eIP7U5h

#Python program to generate MD5 of String data
"""

import hashlib
m = hashlib.md5()
text = input("Enter String:")
m.update(text.encode('utf-8'))
print(m.hexdigest())